theme: jekyll-theme-midnight
title: Patryk Ptasiński's Portfolio
description: Summarized public opensource projects contributions made by Patryk Ptasiński.
show_downloads: false
google_analytics: UA-81150032-3
